// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAMPwTnSJItNHHuvufsioeeh2IfvBGFsgo',
//     appId: '1:1006385093733:web:93b43c5f723a9affcf7a8c',
//     messagingSenderId: '1006385093733',
//     projectId: 'shoesly-54cf7',
//     authDomain: 'shoesly-54cf7.firebaseapp.com',
//     databaseURL: 'https://shoesly-54cf7-default-rtdb.firebaseio.com',
//     storageBucket: 'shoesly-54cf7.appspot.com',
//     measurementId: 'G-20ERLN3GF1',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAWjzvrMwxysEmbRF_bvC3E7UM0fTQCA68',
//     appId: '1:1006385093733:android:2b757f14c7e76d0dcf7a8c',
//     messagingSenderId: '1006385093733',
//     projectId: 'shoesly-54cf7',
//     databaseURL: 'https://shoesly-54cf7-default-rtdb.firebaseio.com',
//     storageBucket: 'shoesly-54cf7.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBPoL9GgYM2tOFREaxoREwdC1quIJ2mlMA',
//     appId: '1:1006385093733:ios:ffea0031bda1d4f8cf7a8c',
//     messagingSenderId: '1006385093733',
//     projectId: 'shoesly-54cf7',
//     databaseURL: 'https://shoesly-54cf7-default-rtdb.firebaseio.com',
//     storageBucket: 'shoesly-54cf7.appspot.com',
//     iosBundleId: 'com.shoesly.shoesly',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyBPoL9GgYM2tOFREaxoREwdC1quIJ2mlMA',
//     appId: '1:1006385093733:ios:ffea0031bda1d4f8cf7a8c',
//     messagingSenderId: '1006385093733',
//     projectId: 'shoesly-54cf7',
//     databaseURL: 'https://shoesly-54cf7-default-rtdb.firebaseio.com',
//     storageBucket: 'shoesly-54cf7.appspot.com',
//     iosBundleId: 'com.shoesly.shoesly',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyAMPwTnSJItNHHuvufsioeeh2IfvBGFsgo',
//     appId: '1:1006385093733:web:389cdad9117e59cdcf7a8c',
//     messagingSenderId: '1006385093733',
//     projectId: 'shoesly-54cf7',
//     authDomain: 'shoesly-54cf7.firebaseapp.com',
//     databaseURL: 'https://shoesly-54cf7-default-rtdb.firebaseio.com',
//     storageBucket: 'shoesly-54cf7.appspot.com',
//     measurementId: 'G-XQ78G4NBQ1',
//   );
// }